title: Anurag Mishra
logo: https://github.com/starrynightishere/starrynightishere.github.io/blob/main/ai-generated-8256537_1920.jpg
description: A personal website using GitHub Pages
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have oneplugins:
- jekyll-remote-theme 
