title: Anurag Mishra
description: Innovating in AI and software with a vision of the future inspired by science fiction.
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
fontawesome:
  cdn: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
