title: Anurag Mishra
logo: https://github.com/starrynightishere/starrynightishere.github.io/blob/main/ai-generated-8256537_1920.jpg
description: A personal website using GitHub Pages
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme 
